export enum statusMeterEnum {
    INSTALLED = 'INSTALLED',
    DISCOVERED = 'DISCOVERED',
    RECONCILIATION_PENDING = 'RECONCILIATION_PENDING',
    ACTIVATION_PENDING = 'ACTIVATION_PENDING',
    REMOVED = 'REMOVED',
    RECONCILED = 'RECONCILED',
    REJECTED = 'REJECTED',
    ACTIVATED = 'ACTIVATED',
    ALL = 'ALL',
    FAILED = 'FAILED',
    PROVISIONED = 'PROVISIONED',
}
